---
tenants:
  - name: JORGE
    mac_vrf_vni_base: 10000
    redistribute_mlag_ibgp_peering_vrfs: false

    l2vlans:
      - id: 55
        name: VLAN55
      - id: 56
        name: VLAN56
      - id: 57
        name: VLAN57
      - id: 58
        name: VLAN58

    vrfs:
      - name: vr-3030
        vrf_vni: 30
        svis:
          - id: 3030
            # SVI Description
            name: vlan3030
            enabled: true
            ip_address_virtual: 172.30.30.1/24
        
        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: 172.30.30.254

      - name: vr-4040
        vrf_vni: 40
        svis:
          - id: 3040
            # SVI Description
            name: vlan3040
            enabled: true
            ip_address_virtual: 172.30.40.1/24

        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: 172.30.40.254      
